### ISSUE TITLE
Online demo json 文件 404

### ISSUE THREAD

**Issue by ThomasChan** [simaQ/G2-demo#1]
Online demo 中下列 6 个文件中 jquery 请求的 data 下的 json 文件 404:

examples/others/line.md
examples/others/map-albers-project.md
examples/others/map-bubble.md
examples/others/map.md
examples/others/point-jitter.md
examples/others/tree.md

建议修复一下.

**Comment by simaQ** [comment]
感谢反馈，已修复。
